---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 1094868015282352128-fTjFTdXroeXg8mD84Pc7b9id1fYjQl
:access_token_secret: mQo6a2eZzE0ZLvXmdSvRZuQy5cuslkmQaS3YV13wjavXT
